import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('simulation_time_change.csv')
df_plot = df[df['Simulation Time(s)'] != 'Average']
df_plot = df_plot.set_index('Simulation Time(s)')
fig, ax1 = plt.subplots(figsize=(12, 6))
ax1.plot(df_plot.index, df_plot['Delay(ms)'], label='Delay(ms)', marker='o', color='tab:blue')
ax1.set_xlabel('Simulation Time(s)')
ax1.set_ylabel('Delay(ms)', color='tab:blue')
ax1.tick_params(axis='y', labelcolor='tab:blue')
ax1.set_ylim([0, df_plot['Delay(ms)'].max() * 1.1])
ax2 = ax1.twinx()
ax2.plot(df_plot.index, df_plot['Throughput(bps)'], label='Throughput(bps)', marker='s', color='tab:green')
ax2.set_ylabel('Throughput(bps)', color='tab:green')
ax2.tick_params(axis='y', labelcolor='tab:green')
ax2.set_ylim([0, df_plot['Throughput(bps)'].max() * 1.1])
ax3 = ax1.twinx()
ax3.spines['right'].set_position(('outward', 60))
ax3.plot(df_plot.index, df_plot['Drop Rate(%)'], label='Drop Rate(%)', marker='^', color='tab:red')
ax3.set_ylabel('Drop Rate(%)', color='tab:red')
ax3.tick_params(axis='y', labelcolor='tab:red')
ax3.set_ylim([0, df_plot['Drop Rate(%)'].max() * 1.1])
plt.title('Network Metrics by Simulation Time Change')
fig.legend(loc='upper right')
plt.grid(True)
plt.tight_layout()
plt.savefig('time.png')
