import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('comparison.csv')
df_tcp = df[(df['Protocol'] == 'TCP') & (df['No. of run'] != 'Average')]
df_udp = df[(df['Protocol'] == 'UDP') & (df['No. of run'] != 'Average')]
fig, axs = plt.subplots(2, 1, figsize=(12, 10), sharex=True)
ax1 = axs[0]
ax1.plot(df_tcp['No. of run'], df_tcp['Delay(ms)'], label='TCP Delay(ms)', marker='o', color='tab:blue')
ax1.set_ylabel('Delay(ms)', color='tab:blue')
ax1.tick_params(axis='y', labelcolor='tab:blue')
ax1.legend(loc='upper left')
ax2 = ax1.twinx()
ax2.plot(df_tcp['No. of run'], df_tcp['Throughput(bps)'], label='TCP Throughput(bps)', marker='s', color='tab:green')
ax2.set_ylabel('Throughput(bps)', color='tab:green')
ax2.tick_params(axis='y', labelcolor='tab:green')
ax2.legend(loc='upper center')
ax3 = ax1.twinx()
ax3.spines['right'].set_position(('outward', 60))
ax3.plot(df_tcp['No. of run'], df_tcp['Drop Rate(%)'], label='TCP Drop Rate(%)', marker='^', color='tab:red')
ax3.set_ylabel('Drop Rate(%)', color='tab:red')
ax3.tick_params(axis='y', labelcolor='tab:red')
ax3.legend(loc='upper right')
ax1 = axs[1]
ax1.plot(df_udp['No. of run'], df_udp['Delay(ms)'], label='UDP Delay(ms)', marker='o', color='tab:blue')
ax1.set_xlabel('No. of run')
ax1.set_ylabel('Delay(ms)', color='tab:blue')
ax1.tick_params(axis='y', labelcolor='tab:blue')
ax1.legend(loc='upper left')
ax2 = ax1.twinx()
ax2.plot(df_udp['No. of run'], df_udp['Throughput(bps)'], label='UDP Throughput(bps)', marker='s', color='tab:green')
ax2.set_ylabel('Throughput(bps)', color='tab:green')
ax2.tick_params(axis='y', labelcolor='tab:green')
ax2.legend(loc='upper center')
ax3 = ax1.twinx()
ax3.spines['right'].set_position(('outward', 60))
ax3.plot(df_udp['No. of run'], df_udp['Drop Rate(%)'], label='UDP Drop Rate(%)', marker='^', color='tab:red')
ax3.set_ylabel('Drop Rate(%)', color='tab:red')
ax3.tick_params(axis='y', labelcolor='tab:red')
ax3.legend(loc='upper right')
plt.suptitle('Network Metrics by Seperate Protocol')
plt.grid(True)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.savefig('comparison.png')